import React, {useEffect, useState} from 'react'

export default function ExplanationCard({text}){
  const [out,setOut] = useState('')
  useEffect(()=>{
    let i=0
    setOut('')
    const id = setInterval(()=>{
      if(i>= (text||'').length){ clearInterval(id); return }
      setOut(prev=>prev + (text||'')[i]); i++
    },30)
    return ()=>clearInterval(id)
  },[text])

  return (
    <div className="bg-white p-4 rounded-2xl shadow mt-4">
      <div className="flex items-center justify-between"><div className="font-semibold">AI Valuation Analyst</div><div className="text-xs text-gray-400">Powered by Groq LLaMA3</div></div>
      <div className="mt-3 text-sm text-gray-700">{out}</div>
      <div className="text-xs text-gray-400 mt-3">Analysis generated by Groq LLaMA3 • IntelliValue v2.0</div>
    </div>
  )
}
